name: squirrels_box_2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  camera: ^0.11.0+1
  convert: ^3.1.1
  dio: ^5.4.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.1.4
  google_fonts: ^6.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.3
  pointycastle: ^3.9.1
  shared_preferences: ^2.3.2

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/svg/

  uses-material-design: true
